language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

before_script:
 - if [ "$TRAVIS_PHP_VERSION" = "5.3" ]; then export COVERAGE=--coverage-clover=build/logs/clover.xml; else export COVERAGE=; fi

script:
 - phpunit $COVERAGE

after_success:
 - if ( test ! -z $COVERAGE ); then wget https://scrutinizer-ci.com/ocular.phar; fi
 - if ( test ! -z $COVERAGE ); then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml ;fi
