language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script:
 - phpunit

after_success:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
